export const hotelExamples = [
  { slug: "cat-duet", title: "Orange Studio Cat Duet", category: "Pets", subtitle: "Two personalities. One microphone.", description: "A tabby and a gray cat trade small head bobs and playful gestures in a warm orange studio.", cast: "pets", prompt: "Create a playful duet with my two cats in an orange studio. Keep the first cat on the left and the second on the right. Alternate gentle head bobs and small paw movements below their faces. Keep their fur markings and natural anatomy consistent. Use a fixed medium-wide camera and original instrumental hip-hop audio.", tip: "Use a separate, well-lit photo of each cat with its eyes, ears, and fur markings clearly visible." },
  { slug: "cat-dog-duet", title: "Cat & Corgi Mic Check", category: "Pets", subtitle: "An unlikely duo finds its rhythm.", description: "A cream cat and a corgi share the spotlight, reacting to one another beside a suspended microphone.", cast: "pets", prompt: "Create an orange-studio duet using my cat and dog photos. Keep the first pet on the left and the second on the right. The cat leads with gentle head movements while the dog reacts, then they exchange roles. Preserve their different sizes, fur markings, and natural anatomy. Keep the camera steady and the gestures small.", tip: "Choose photos with similar camera angles. Describe which pet leads rather than asking for complicated simultaneous actions." },
  { slug: "grandparents-duet", title: "Golden Years, Fresh Flow", category: "People", subtitle: "Style has no age limit.", description: "An original older couple brings a relaxed, expressive performance to a minimal orange stage.", cast: "duet", prompt: "Create a relaxed music-performance duet using my two portraits. Keep the first person on the left and the second on the right, preserving their faces, hairstyles, and outfits. Use an orange studio, soft frontal light, and a hanging microphone. Let them exchange confident head nods and small hand gestures. Keep both faces visible in a steady medium-wide frame.", tip: "Upload one unobstructed portrait per performer. Similar lighting helps the two references feel at home in the same scene." },
] as const;
export const hotelPrompts = [
  { id: "classic-duet", title: "The classic orange-studio duet", category: "Duet", cast: "duet", description: "A clear starting point for two performers and a steady camera.", text: hotelExamples[2].prompt },
  { id: "pet-mic-check", title: "Pet mic check", category: "Pets", cast: "pets", description: "Small movements, distinct markings, and a playful exchange.", text: hotelExamples[0].prompt },
  { id: "solo-spotlight", title: "Solo spotlight", category: "Solo", cast: "solo", description: "One portrait becomes a confident studio performance.", text: "Create a solo music-performance video using my portrait. Keep my face, hairstyle, and outfit consistent. Place me in an orange studio with a hanging microphone and soft front light. Use relaxed head nods and confident hand gestures below the face. Keep a steady medium-wide camera, original instrumental hip-hop audio, and no captions or logos." },
  { id: "cinematic-push", title: "A cinematic slow push-in", category: "Duet", cast: "duet", description: "Bring the camera a little closer without losing either face.", text: "Keep both performers in the orange studio with one hanging microphone. Use a very slow push-in from a medium-wide frame, keeping both faces visible. Add warm, soft lighting and restrained gestures. The left performer leads while the right reacts, then they exchange roles. Preserve both identities and outfits throughout." },
  { id: "rooftop-solo", title: "Rooftop after hours", category: "Solo", cast: "solo", description: "Change the setting while keeping a simple performance.", text: "Use my uploaded portrait for a solo rooftop music performance at blue hour. Keep my identity and outfit consistent. Use a fixed medium shot, soft light on the face, a microphone, relaxed head nods, and small confident gestures. Keep the skyline softly out of focus. Original instrumental hip-hop audio, no captions or logos." },
  { id: "calmer-duet", title: "A calmer second take", category: "Duet", cast: "duet", description: "A gentle alternative when you want fewer moving parts.", text: "Create a calm orange-studio duet using my two portraits. Keep the first performer on the left and the second on the right. Use a locked medium-wide camera and soft frontal lighting. Let them alternate subtle head nods with their hands kept below the face. Preserve both faces and outfits, and avoid sudden camera moves." },
] as const;
export function hotelPromptHref(prompt: string, cast: string) {
  return `/?${new URLSearchParams({ prompt, cast }).toString()}`;
}
