import { publicPageMetadata } from "@/lib/page-metadata";
import HotelSiteFooter from "@/components/hotel-site-footer";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { hotelGuides } from "@/components/hotel-lobby-content";
import { SITE_URL } from "@/lib/site";
import styles from "@/components/hotel-lobby-content.module.css";
const sections: Record<string, Array<[
    string,
    string
]>> = {
    "how-to-make-hotel-lobby-ai-video": [["1. Start with the right cast", "Open the workspace and choose Solo for one performer, Duet for two people or characters, or Pet duet for two animals. Solo requires one photo; the duet modes require exactly two. The first image places your performer on the left, and the second places them on the right."], ["2. Upload a clear reference for each performer", "Choose sharp photos with even lighting and visible faces. Avoid a collage or a group shot when you can provide one subject per photo. Review the upload order before continuing."], ["3. Set the direction", "Leave the description empty to use the orange-studio preset. Advanced settings let you choose a scene, camera move, visual style, lighting, and performance energy. Add a short description for a specific change; your written request takes priority over the preset."], ["4. Review the generation options", "Check the available duration, output settings, and account credit requirements in the workspace. Submit when the photos and options are ready. A new conversation tracks the job and its result; generation time depends on the queue and request."], ["5. Save and continue", "Review the completed video, download the MP4, or continue the conversation to request another version. Use Recents to return to earlier projects. If you publish with music, choose audio you have permission to use; the preset does not provide the original Hotel Lobby recording."]],
    "hotel-lobby-ai-pets": [["Give every pet its own photo", "A separate image for each pet makes the left-to-right casting explicit. Pick photos that show the eyes, ears, and distinctive markings. A simple background and natural lighting are useful; tiny faces and heavy filters make identity harder to preserve."], ["Choose Pet duet", "Upload the first pet for the left spot and the second for the right. This mode adds direction to preserve fur markings and natural animal anatomy while keeping the two subjects distinct."], ["Keep the performance playful and simple", "Small head bobs, gentle paw movements, and alternating attention at the microphone are a good starting point. Ask for one pet to lead while the other reacts. Avoid piling several complicated actions into a short clip."], ["Review anatomy and identity", "AI motion can introduce visual inconsistencies. Check paws, eyes, markings, and the handoff between performers before downloading. You can continue in the same conversation with a focused adjustment such as calmer movement or a steadier camera."]],
    "hotel-lobby-ai-prompts": [["Start with the preset, then change one thing", "The workspace already supplies a seamless orange studio, a hanging microphone, soft frontal light, and a steady medium-wide camera. You do not need to repeat the whole preset. A short adjustment is often easier to evaluate than a long list of unrelated directions."], ["Describe the camera", "Try a fixed medium-wide frame when both performers need to remain visible. A slow push-in can add emphasis. Fast camera moves or close-ups may make identity and anatomy less consistent."], ["Set lighting and energy", "Choose soft front light for a clean studio look, warm light for a relaxed performance, or neon for a stylized scene. Keep energy direction specific: relaxed head nods, confident gestures below the face, or a playful exchange between the two subjects."], ["Continue without starting over", "In the result conversation, describe the change you want: keep the same performers and orange room, but slow the camera and make the gestures smaller. Follow-up requests retain the conversation context and may require another generation."]]
};
export function generateStaticParams() { return hotelGuides.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: {
    params: Promise<{
        slug: string;
    }>;
}): Promise<Metadata> { const { slug } = await params; const guide = hotelGuides.find(g => g.slug === slug); if (!guide)
    return {}; return publicPageMetadata(`/guides/${slug}`, guide.title, guide.description, undefined, "article"); }
export default async function Guide({ params }: {
    params: Promise<{
        slug: string;
    }>;
}) { const { slug } = await params; const guide = hotelGuides.find(g => g.slug === slug); if (!guide)
    notFound(); return <><main className={styles.article}><header><Link href="/guides">← All studio guides</Link><Link href="/prompts">Explore prompts →</Link></header><p>STUDIO GUIDE · Updated October 2, 2026</p><h1>{guide.title}</h1><p>{guide.description}</p>{sections[slug].map(([title, text]) => <section key={title}><h2>{title}</h2><p>{text}</p></section>)}{slug === "hotel-lobby-ai-prompts" ? <blockquote>Keep the two performers in the orange studio with a hanging microphone. Use a slow push-in, soft warm light, and relaxed head nods. The left performer leads, the right reacts, then they exchange roles. Keep both faces clear and gestures below the face. Original instrumental hip-hop audio, no captions or logos.</blockquote> : null}<nav><Link href="/hotel-lobby-ai">Create your Hotel Lobby AI video →</Link>{hotelGuides.filter(g => g.slug !== slug).map(g => <Link key={g.slug} href={`/guides/${g.slug}`}>{g.title}</Link>)}</nav><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: guide.title, description: guide.description, dateModified: "2026-10-02", datePublished: "2026-10-02", author: { "@type": "Organization", name: "Hotel Lobby AI" }, mainEntityOfPage: `${SITE_URL}/guides/${slug}` }).replace(/</g, "\\u003c") }}/></main><HotelSiteFooter /></>; }
