// Generated by npm run i18n:generate. Do not edit manually.
import en_common from "./en/common.json";
import en_home from "./en/home.json";
import en_seo from "./en/seo.json";
import en_workbench from "./en/workbench.json";
import de_common from "./de/common.json";
import de_home from "./de/home.json";
import de_seo from "./de/seo.json";
import de_workbench from "./de/workbench.json";
import fr_common from "./fr/common.json";
import fr_home from "./fr/home.json";
import fr_seo from "./fr/seo.json";
import fr_workbench from "./fr/workbench.json";
import es_common from "./es/common.json";
import es_home from "./es/home.json";
import es_seo from "./es/seo.json";
import es_workbench from "./es/workbench.json";
import pt_br_common from "./pt-br/common.json";
import pt_br_home from "./pt-br/home.json";
import pt_br_seo from "./pt-br/seo.json";
import pt_br_workbench from "./pt-br/workbench.json";
import ja_common from "./ja/common.json";
import ja_home from "./ja/home.json";
import ja_seo from "./ja/seo.json";
import ja_workbench from "./ja/workbench.json";
import zh_tw_common from "./zh-tw/common.json";
import zh_tw_home from "./zh-tw/home.json";
import zh_tw_seo from "./zh-tw/seo.json";
import zh_tw_workbench from "./zh-tw/workbench.json";

export const LOCALE_RESOURCES = {
  "en": { "common": en_common, "home": en_home, "seo": en_seo, "workbench": en_workbench },
  "de": { "common": de_common, "home": de_home, "seo": de_seo, "workbench": de_workbench },
  "fr": { "common": fr_common, "home": fr_home, "seo": fr_seo, "workbench": fr_workbench },
  "es": { "common": es_common, "home": es_home, "seo": es_seo, "workbench": es_workbench },
  "pt-br": { "common": pt_br_common, "home": pt_br_home, "seo": pt_br_seo, "workbench": pt_br_workbench },
  "ja": { "common": ja_common, "home": ja_home, "seo": ja_seo, "workbench": ja_workbench },
  "zh-tw": { "common": zh_tw_common, "home": zh_tw_home, "seo": zh_tw_seo, "workbench": zh_tw_workbench }
};

import sourceIndex from "./source-index.json";
export const LOCALE_NAMESPACES: readonly string[] = ["common","home","seo","workbench"];
export function getSourceIndex(): Record<string, string> { return sourceIndex; }
// The server already has every locale. Never mutate shared resources per request.
export function registerSourceIndex(index: Record<string, string>, namespaces: readonly string[]): void { void index; void namespaces; }
export function registerLocaleResources(locale: string, resources: Record<string, unknown>): void { void locale; void resources; }
export function hasLocaleResources(locale: string, namespaces?: readonly string[]): boolean {
  const resources = (LOCALE_RESOURCES as Record<string, Record<string, unknown>>)[locale];
  return Object.hasOwn(LOCALE_RESOURCES, locale) && (!namespaces || namespaces.every(namespace => Object.hasOwn(resources, namespace)));
}
export async function loadLocaleResources(locale: string, namespaces?: readonly string[]): Promise<void> {
  if (!hasLocaleResources(locale, namespaces)) throw new Error("Unsupported locale or namespace");
}
