import { SITE_URL } from "@/lib/site";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { hotelExamples, hotelPromptHref } from "@/lib/hotel-library";
import { publicPageMetadata } from "@/lib/page-metadata";
import HotelSiteFooter from "@/components/hotel-site-footer";
import styles from "@/components/hotel-site.module.css";
export function generateStaticParams(){return hotelExamples.map(({slug})=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const item=hotelExamples.find(item=>item.slug===slug);if(!item)return {};return publicPageMetadata(`/examples/${slug}`, item.title, item.description, `/assets/hotel-lobby-ai/demos/rap-v1/${slug}_poster.webp`);}
export default async function Example({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const item=hotelExamples.find(item=>item.slug===slug);if(!item)notFound();return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"VideoObject",name:item.title,description:item.description,thumbnailUrl:`${SITE_URL}/assets/hotel-lobby-ai/demos/rap-v1/${slug}_poster.webp`,contentUrl:`${SITE_URL}/assets/hotel-lobby-ai/demos/rap-v1/${slug}.mp4`,uploadDate:slug==="cat-duet"?"2026-09-30T12:09:20.057Z":slug==="cat-dog-duet"?"2026-09-30T12:11:33.233Z":"2026-09-30T12:09:22.130Z",duration:"PT8S",mainEntityOfPage:`${SITE_URL}/examples/${slug}`}).replace(/</g,"\\u003c")}}/><main className={styles.page}><p className={styles.breadcrumb}><Link href="/examples">Examples</Link> / {item.title}</p><div className={styles.detail}><video controls playsInline preload="metadata" poster={`/assets/hotel-lobby-ai/demos/rap-v1/${slug}_poster.webp`} aria-label={item.title}><source src={`/assets/hotel-lobby-ai/demos/rap-v1/${slug}.mp4`} type="video/mp4"/></video><div><p className={styles.eyebrow}>{item.category} · 8-SECOND ORIGINAL EXAMPLE</p><h1>{item.title}</h1><p>{item.description}</p><Link className={styles.button} href={hotelPromptHref(item.prompt,item.cast)}>Make your own version ↗</Link><h2>Start with the right photos</h2><p>{item.tip}</p><h2>Performance direction</h2><p>{item.prompt}</p><p className={styles.note}>This is a starting direction for a new generation, not a promise to reproduce the sample exactly. Results depend on your photos and settings.</p></div></div><section className={styles.banner}><div><h2>Your first time in the studio?</h2><p>Follow the photo-to-video guide from cast selection to download.</p></div><Link className={styles.button} href="/guides/how-to-make-hotel-lobby-ai-video">Read the walkthrough →</Link></section></main><HotelSiteFooter/></>}
