import Link from "next/link";
import styles from "./hotel-lobby-content.module.css";
export const hotelFaqs = [
    ["What is a Hotel Lobby AI video?", "A short AI music-performance video inspired by the orange studio, hanging microphone, and duet format. Upload photos to cast friends, characters, or pets in your own scene."],
    ["How many photos do I need?", "Solo needs one photo. Duet and Pet duet need two: the first upload is the left performer and the second is the right performer. Choose clear images with an unobstructed subject."],
    ["Do I need to write a prompt?", "No. The preset supplies the orange studio, microphone, lighting, and performance direction. Add a description or use advanced settings when you want to change the scene, camera, or mood."],
    ["Does the video include the original Hotel Lobby song?", "The preset requests original instrumental hip-hop audio. It does not include the original song, clone a singer’s voice, or guarantee the original choreography. Generated motion and audio vary."],
    ["Can I make Hotel Lobby AI videos with cats or dogs?", "Yes. Select Pet duet and upload one photo per pet. Clear eyes, visible fur markings, and a simple background help the model keep the two subjects distinct."],
    ["Is Hotel Lobby AI free?", "You can explore the workspace and examples without a subscription. Generation and downloads follow the credit balance, access rules, and pricing shown in your account. Review the displayed cost before submitting."],
    ["Can I change my video after generating it?", "Continue in the same conversation to request a change to the performance or visual direction. New generation requests may use additional credits; completed results remain in your recent projects."],
    ["What format can I download?", "The workspace generates MP4 video, with a vertical composition by default. Duration and other available options appear in the workspace before you generate."]
];
export const hotelGuides = [
    { slug: "how-to-make-hotel-lobby-ai-video", title: "How to make a Hotel Lobby AI video", description: "From your first photo to a finished orange-studio performance." },
    { slug: "hotel-lobby-ai-pets", title: "Make a Hotel Lobby cat or dog duet", description: "Photo tips and performance ideas for two unmistakable pets." },
    { slug: "hotel-lobby-ai-prompts", title: "Hotel Lobby AI prompts and ideas", description: "Customize the camera, lighting, and energy of your clip." }
];
export function HotelLobbyExamples() { return <section className={styles.section} id="examples"><p className={styles.eyebrow}>MADE WITH THE HOTEL LOBBY PRESET</p><h2>A little orange. A lot of personality.</h2><p className={styles.lead}>Original AI examples from our studio. Choose your cast and make the next one your own.</p><div className={styles.examples}>{[["cat-duet", "The cat duet", "Two cats. One mic. Their own rhythm."], ["cat-dog-duet", "An unlikely duo", "A cat and corgi share the spotlight."], ["grandparents-duet", "Generations of cool", "A relaxed performance with plenty of character."]].map(([slug, title, description]) => <figure key={slug}><video controls playsInline preload="none" poster={`/assets/hotel-lobby-ai/demos/rap-v1/${slug}_poster.webp`} aria-label={title}><source src={`/assets/hotel-lobby-ai/demos/rap-v1/${slug}.mp4`} type="video/mp4"/></video><figcaption><h3><Link href={`/examples/${slug}`}>{title}</Link></h3><p>{description}</p><span>8 seconds · Original AI example</span></figcaption></figure>)}</div></section>; }
export function HotelLobbyContent() {
    return <div className={styles.content}>
    <HotelLobbyExamples />
    <section className={styles.intro}><p className={styles.eyebrow}>THE IDEA BEHIND THE STUDIO</p><h2>What is Hotel Lobby AI?</h2><p>Hotel Lobby AI turns ordinary portraits into a short music-performance scene: an orange backdrop, a suspended microphone, and a cast with its own personality. Make a solo performance, trade the spotlight with a friend, or put your pets in the booth.</p><p>The preset handles the starting direction. Your photos define the performers; your optional description makes the scene yours.</p></section>
    <section className={styles.section} id="how-it-works"><p className={styles.eyebrow}>YOUR PHOTOS. YOUR PERFORMANCE.</p><h2>How to make your Hotel Lobby AI video</h2><ol className={styles.steps}>{[["Choose your cast", "Pick Solo, Duet, or Pet duet. Upload one clear photo for each performer, in left-to-right order."], ["Make the scene yours", "Start with the orange-studio preset, or adjust the scene, camera, visual style, lighting, and performance energy."], ["Generate, review, download", "Submit your request, follow the generation in your conversation, and download the finished MP4. Return to Recents to find it again."]].map(([title, body], i) => <li key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{body}</p></li>)}</ol></section>
    <section className={styles.section}><p className={styles.eyebrow}>GET A BETTER FIRST TAKE</p><h2>Great performances start with clear photos</h2><div className={styles.tips}><p>Use a well-lit portrait with an unobstructed face. Keep each performer in a separate image so their position is unambiguous.</p><p>For pets, show their eyes and distinctive fur markings. Keep prompts focused on a few simple movements so identities and anatomy stay easier to recognize.</p><p>Want a different mood? Try a slow camera push-in, warm light, or a playful performance. Your written adjustments take priority over the preset.</p></div></section>
    <section className={styles.section} id="guides"><h2>Ideas for your next take</h2><div className={styles.guides}>{hotelGuides.map(guide => <Link href={`/guides/${guide.slug}`} key={guide.slug}><span>THE STUDIO GUIDE</span><h3>{guide.title}</h3><p>{guide.description}</p><b>Read the guide →</b></Link>)}</div></section>
    <section className={styles.section} id="faq"><h2>Hotel Lobby AI questions, answered</h2><div className={styles.faq}>{hotelFaqs.map(([q, a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
    <section className={styles.cta}><p className={styles.eyebrow}>YOUR TURN AT THE MIC</p><h2>One photo away from your first take.</h2><p>Bring a friend, a pet, or just yourself.</p><Link href="/">Create a Hotel Lobby AI video ↑</Link></section>
    <footer className={styles.footer}><Link href="/">Hotel Lobby AI</Link><nav aria-label="Footer"><Link href="/examples">Examples</Link><Link href="/prompts">Prompts</Link><Link href="/guides">Guides</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/refund-policy">Refund policy</Link><Link href="/pricing">Pricing</Link></nav><p>© {new Date().getFullYear()} Hotel Lobby AI · Powered by Vismuse.<br />An independent creative tool. Not affiliated with the artists, COLORS, TikTok, or CapCut.</p></footer>
    </div>;
}
